### ISSUE TITLE
When will JSAPI 4.x support georeferenced image layer similar to MapImageLayer in 3x

### ISSUE THREAD

**Issue by wo4861069** [Esri/jsapi-resources#150]
求教esri的大神，arcgis for js 4.x 什么时候添加图片叠加的layer 类似3.x的MapImageLayer，会是一下个版本吗？

I am reporting an issue with 

- [ ] TypeScript definitions
- [ ] another resource in this repository

**Comment by fangli88** [comment]
In order for more people to understand this issue, the English translation of this issue is:
_When will JSAPI 4.x support georeferenced image layer similar to MapImageLayer in 3x. Will that be next release?_

We are still working on adding support for this feature. But we don't have a timeline yet.

**Comment by wo4861069** [comment]
Why there is no timetable? This function is very useful. I hope you can see it in the next version. Thank you

**Comment by boualikamel** [comment]
same issue ... the georeferenced option and the snappingManager is usefull too !

**Comment by ubatsukh** [comment]
@wo4861069  and @boualikamel could you please provide more information on what exactly you want from this feature in 4.x? Also do you have any suggestions how or what can be be improved from the 3.x version?

We are planning to add this feature in 4.x and would like to get feedback from users so that your requirements are covered. 

Thanks.

**Comment by bsvensson** [comment]
Version 4.24 (released in June 2022) supports adding georeferenced images using the new MediaLayer - see https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-MediaLayer.html and https://developers.arcgis.com/javascript/latest/4.24/#medialayer
