### ISSUE TITLE
Webpack & CoordinateConversion widget

### ISSUE THREAD

**Issue by eyosef** [Esri/jsapi-resources#203]
I am reporting an issue with 

- [ ] TypeScript definitions
- [X] another resource in this repository

________________________________________________________________________________________

- I'm running into a bug leveraging `CoordinateConversion` widget with the webpack configurations outlined in `webpack/demo`. After forking/cloning this repo, I created a new instance of `CoordinateConversion` and added it the the mapview;

``` typescript
// demo/src/index.ts

// ....
// ....
// ....
const coordinateConversion = new CoordinateConversion({
  view,
  mode: 'live',
})

map.addMany([layer1, layer2])
view.ui.add(coordinateConversion, 'bottom-left')
```

- When testing the `CoordinateConversion` widget locally, I noticed the performance is significantly slower compared to the [sample provided in the documentation](https://developers.arcgis.com/javascript/latest/sample-code/widgets-coordinateconversion/index.html). I noticed there were performance issues with the options DDM, DD, DMS, MGRS, USNG and UTM. In the console, I'm getting the error `Uncaught (in promise) ReferenceError: global is not defined`. The error specifically looks like this;

![Screen Shot 2020-02-19 at 12 17 28 PM](https://user-images.githubusercontent.com/9040867/74857553-d5847a80-5311-11ea-97e0-018a5b5e22d3.png)

Are there any considerations that should be made when leveraging the `CoordinateConversion` widget with `@arcgis/webpack-plugin`? Does `esri/core/promiseUtils` need to be explicitly leveraged with the `CoordinateConversion` widget to ensure the widget performs as fast as the [sample code](https://developers.arcgis.com/javascript/latest/sample-code/widgets-coordinateconversion/index.html)?

**Comment by COV-GIS** [comment]
Somewhat related...webpack has an issue importing/loading `esri/geometry/coordinateFormatter`. I'm not sure what the underlying issue is with the module and it's exports but that error is related to loading `coordinateFormatter` like...

```javascript
import coordinateFormatter from 'esri/geometry/coordinateFormatter';
coordinateFormatter.load();
```

The fix is to load like...
```javascript
import {
  load as coordinateFormatterLoad,
  toLatitudeLongitude
} from 'esri/geometry/coordinateFormatter';
coordinateFormatterLoad();
```

Doesn't really help with a widget itself. I guess I don't even know if it's `coordinateFormatter` in `CoordinateConversion` widget but exact same errors. I wonder if importing and calling the offending module's `load` before initializing the widget my get around the error.

FYI @odoe I meant to create an issue about this in webpack plugin a while ago but failed to do so. The `projection` module has the same issue I believe.

**Comment by eyosef** [comment]
Great point @COV-GIS , thanks for sharing!
