### ISSUE TITLE
arcgis-js-api-sample-app is not found in this npm registry

### ISSUE THREAD

**Issue by lingpri** [Esri/jsapi-resources#26]
I get the error below: please, advice.

25 error npm  v2.15.1
26 error code E404
27 error 404 Registry returned 404 for GET on https://registry.npmjs.org/arcgis-js-api-sample-app
27 error 404
27 error 404 'arcgis-js-api-sample-app' is not in the npm registry.
27 error 404 You should bug the author to publish it (or use the name yourself!)
27 error 404
27 error 404 Note that you can also install from a
27 error 404 tarball, folder, http url, or git url.
28 verbose exit [ 1, true ]

**Comment by jgravois** [comment]
you are encountering that error because we haven't published any packages to npm called `arcgis-js-api-sample-app`.

if you navigate into the folder on your own machine where this package.json file is located and call 'npm install' with no other arguments, the appropriate dependencies will be fetched from npm and no errors will be thrown.

https://docs.npmjs.com/cli/install

**Comment by lingpri** [comment]
The problem was with jdk version 1.6, after upgrading to jdk1.7, i was able to run the build sucessfully. Will close the issue. Just curious why do we have a dependency on java for the front end tooling?

Thanks..
Priya

**Comment by jgravois** [comment]
pretty sure that's inherited from Dojo.
