### ISSUE TITLE
TypeScript: FeatureLayer deleteAttachments returns wrong type

### ISSUE THREAD

**Issue by COV-GIS** [Esri/jsapi-resources#361]
Should be `Promise<FeatureEditResult[]>` and not `Promise<FeatureEditResult>`;

The docs are also wrong: https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-FeatureLayer.html#deleteAttachments

**Comment by ubatsukh** [comment]
Thanks for letting us know. We will update the typings in our next release.

**Comment by sandrooco** [comment]
@ubatsukh is this repo also meant for such issues? I was searching for a GH Repo for @arcgis/core and found only this examples repo...
Would be cool if it works here. :)

**Comment by andygup** [comment]
Hi @sandrooco, the majority of ArcGIS JS API questions are best asked on the community site because that has a huge number of users that can help answer questions and it has high visibility for other users looking for answers to similar questions: https://community.esri.com/t5/arcgis-api-for-javascript-questions/bd-p/arcgis-api-for-javascript-questions. For questions about the @arcgis/core samples and its implementation in various frameworks and module bundlers it's also okay to ask those questions in this repo (which houses the @arcgis/core samples).

**Comment by ubatsukh** [comment]
@COV-GIS the typings will be updated at version 4.23.
