### ISSUE TITLE
*d.ts module export format: default or '='

### ISSUE THREAD

**Issue by nickcam** [Esri/jsapi-resources#37]
Hi all,

Just wondering if there's a compelling reason as to why all of the modules in *.d.ts export in this format?
```
declare module "esri/Map" {
    import Map = __esri.Map;
    export = Map;
}
```
I would have thought since every module only exports a single object, using a default export would be better. 
```
declare module "esri/Map" {
    import Map = __esri.Map;
    export default Map;
}
```

Certainly makes importing easier - well in my case it does anyway, which involves systemjs/ngc/rollup for dev and prod builds of an Angular 2 app. 

I realise dojo exports the same way, but is it really necessary? Would prefer to use the official typings instead of editing after importing.

Perhaps it's possible to have multiple official typings per api?

Thanks,
Nick

**Comment by nickcam** [comment]
Just found out the current typings will work in my case when setting the following compilerOption.
```
"allowSyntheticDefaultImports": true
```

Still think the question is valid, but certainly no point in having multiple typings files with such a simple workaround for these tools/cases.
thanks.

**Comment by dasa** [comment]
When I try this, the emitted js file is still looking for a `default` property on the imported module. Are you able to workaround this?

**Comment by dasa** [comment]
Closing this since it sounds like just using `allowSyntheticDefaultImports` is all you need.
https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#support-for-default-import-interop-with-systemjs

**Comment by nickcam** [comment]
It's true that setting this flag is all I need to do to workaround the typescript compile time using systemjs...I still think `export default` should be considered though.

BTW - I wasn't getting errors using the default property as I am using [esri-system-js](https://github.com/Esri/esri-system-js) to load the esri modules. This adds the module as a property called "default" of the import.

**Comment by b0** [comment]
Hi,

just lost days trying to make this work. Try adding esri and typings to [Angular 2 Quickstart app](https://github.com/angular/quickstart) and you will be getting compiler errors because default compilerOptions are now [commonjs](https://github.com/angular/quickstart/blob/master/tsconfig.json#L4) and allowSyntheticDefaultImports  is not set. 

Seams to me that .d.ts file should include "export default" because nothing works with default tsconfig.json and its impossible to know why stuff doesn't work.

**Comment by b0** [comment]
@dasa any thoughts on this?

**Comment by dasa** [comment]
> Seams to me that .d.ts file should include "export default"

We can't make this change since we also need to support TypeScript users who are just using the CDN and vanilla JS users. The definition file needs to reflect the implementation which does not include `.default` properties on the exported modules.

Here's are a couple of examples of using Angular 2 with TypeScript and the ArcGIS JavaScript API that may be helpful:

https://github.com/jwasilgeo/angular2-esri-playground
https://github.com/tomwayson/angular2-esri-example

**Comment by b0** [comment]
Hi,

I did saw those two examples but they work because tsconfig.json and compiler options are different than default compiler options you get when start new Angular 2 app. You'll get it if you look at Angular 2 Quickstart app on github and tsconfig.json there. 

It's almost impossible to know why you can't just add esri-system-js and typing in quickstart tutorial and make it work - it's hard to know there is difference in tsconfig.json and compiler options and you need to change it there.

Maybe there is some other way typings can be "fixed" so they just work with default compiler options ?

I highlighted differences on your examples and quickstart here:
[esri-playground](https://github.com/jwasilgeo/angular2-esri-playground/blob/master/tsconfig.json#L4)
[esri-example](https://github.com/tomwayson/angular2-esri-example/blob/master/tsconfig.json#L4)
[Angular2 Quickstart](https://github.com/angular/quickstart/blob/master/tsconfig.json#L4)

So, you can't just add esri-system-js and typing to quickstart and expect it to work - it doesn't work.

Any workarounds?  Some better fix? Maybe some directions/notes can be written on this repo readme? 

Best regards

**Comment by Robophil** [comment]
geez.. it's been two day now, biting my ass of f trying to solve this. I had to create an issue here https://github.com/systemjs/systemjs/issues/1515#issuecomment-264248790 now finding myself here.

Anyway to resolve this `default`? for those who might loose days to this also.
this works fine, but with warning from vscode and you loose all the intellisense support, but at least it works.
```javascript
import arcgisUtils from 'esri/arcgis/utils';
```
