### ISSUE TITLE
Attachments widget doesn't work with versions

### ISSUE THREAD

**Issue by rustygreen** [Esri/jsapi-resources#412]
**Describe the bug**
When using the attachments widget with a layer set to a specific GDB version, the attachments widget will not display attachments (from that version). 

In the example below, there is an attachment associated with the record on the right hand side (created in that version), but it does not show up in the list:
![image](https://user-images.githubusercontent.com/1774477/168307580-0fc6eb5f-fd21-43fd-873f-7a2466f75d09.png)

**Expected behavior**
It is expected that when you use the attachments widget with a layer that has a [gdbVersion](https://developers.arcgis.com/javascript/latest/api-reference/esri-layers-FeatureLayer.html#gdbVersion) set, it will display attachments created in that version - otherwise editing within a version and using attachments doesn't work.

**Reproduce the issue**
1. Add a feature layer with a GDB version set.
2. Use the attachments widget with that layer.
3. Save an attachment (within that GDB version)
4. The attachments widget will not show any attachments (the query will not return attachments from that version)

**ArcGIS Environment** 
 - ArcGIS Enterprise 10.9.1
 - Branch versioned data (same behavior with traditional versioning as well though)

**Additional context**
There was a support ticket opened with Esri for this issue many months ago with no resolution: **ENH-000146767**

**Comment by hgonzago** [comment]
Thanks for letting us know the specifics on this. There are outstanding issues we intend to address for attachment work within the Editor.  In addition to attachments, we also are looking into supporting workflows with versioned data. The enhancement was logged NOT with the JavaScript API but rather the REST API as the issue lies with the underlying feature service since `queryAttachment` doesn't support `gdbVersion` as a request parameter. Since this is the case,  it returns incorrect or incomplete information. 

I have contacted the correct people in Support to circle back on this as well.

**Comment by andygup** [comment]
Hi @rustygreen I'm going ahead and closing this since Support will be circling back.  

Please note, for future issues the [ArcGIS API for JavaScript community page](https://community.esri.com/t5/arcgis-api-for-javascript/ct-p/arcgis-api-for-javascript) offers significantly greater visibility for posting questions as well as for others who may be searching for answers.
