### ISSUE TITLE
qustion: For arcgis api, should I use esri-loader or esm(@arcgis/core)

### ISSUE THREAD

**Issue by webmapLee** [Esri/jsapi-resources#422]
hello,everyone, i've been struggling with shoule i use esri-loader or esm
## esri-loader
previously, i have been using esri-loader,everytime i refrence the modules, i have to get the modules by the promise function loadModules, it's a bad experience,  usually, i will request the modules i need during app initialization,after all the modules are loaded, i will perform other tasks such as loading layer, loading widgets,etc, the another way is to request the modules which i will cache when load first  on demand，anyway,the develop experience is awkward, in particular i can't use es6 class syntax to implement inheritance。

## @arcgis/core
when i see the esm library  @arcgis/core， i am excited, but when i use it，i ran into some tough problems
**our tech stack is**: **vue3+typescript+webpack5+calcite-components+arcgis api for javascript** 
when i use @arcgis/core, since each module in @arcgis/core has many dependencies, and there are a lot of modules which i need refrence,in addtion,i also need to do module extraction optimization,this causes webpack to take a long time to bundle, and the size of bundled code is large, even if i did packaging optimization, or i just copy the @arcgis/core to my dist, you know ,the size of the @arcgis/core package code requires more than 18 M,and the size of assets is more than 24M,and there are a lot of code files which affects my http concurrent request

##then my qustions are 
1.When should I use amd(esri-loader) and when should I use amd(@arcgis/core)
2.when i use @arcgis/core ,is there any way i can improve the speed of packing with webpack, or i use other bundler tools like esbuild snowpack or bun, Is there any solution that can not only improve the packaging speed, but also reduce the packaging size and the number of packaging files

## idea
now i an thinking publish a independent service @arcgis/core and refrence it through systemjs

**Comment by andygup** [comment]
Hi @webmapLee for your first question you might benefit from reading through the Developer Tooling section of our SDK starting on this page: https://developers.arcgis.com/javascript/latest/tooling-intro/.  For new projects we recommend using ES modules @arcgis/core. Also, here's a slightly older [blog post](https://www.esri.com/arcgis-blog/products/js-api-arcgis/announcements/arcgis-api-for-javascript-working-with-frameworks-and-build-tools-just-got-easier-part-2/). I have a new blog post coming out today that also talks about ES modules on the ArcGIS Blog. I'll try to remember to post a link here when it goes live.

For question 2, if you provide a github sample that demonstrates a specific issue we can take a look. 

If you feel you would benefit from an extensive conversation about your architecture there are also several options. Are you attending the User Conference in San Diego this summer? If so, then we can make arrangements for you to talk to someone. We can also have you get in contact with your sales rep about engaging Professional Services or a Business Partner.

**Comment by webmapLee** [comment]
thank you for your answer, i will develop a demo,  about the conference ,i really really want to go ,but i don't think i have the chance , i am in china now,  i hope i can participate online

**Comment by odoe** [comment]
On the bundle sizes, when using ESM, you are optimizing the build and deploying. With esri-loader, you are still loading as much, if not more code, you just don't have to deploy it. There are only a few edge cases where esri-loader might be a better choice over ESM, and that usually falls into frameworks and build tools that leverage server side rendering. Otherwise, ESM is going to be the preferred method. You also probably don't need to copy our assets over, we load them from the CDN by default. The only time you would want to copy the assets is if you need to sandbox your app from the outside (in which case esri-loader has issues as well), you want to build our sass files, or maybe use custom workers. Other than that, no real need to copy assets over.

**Comment by webmapLee** [comment]
the demo repository url:https://github.com/webmapLee/arcgis-esm-demo

## it's just a simple demo, but
### buildTime:
![image](https://user-images.githubusercontent.com/20334500/175471918-9fdb02e9-6ce9-49c3-ac9a-5c33ad8ce0b9.png)
### server start time
<img width="814" alt="e929a27bfc5bead28332e12402715ec" src="https://user-images.githubusercontent.com/20334500/175471823-f5578cbb-1b68-4505-8ed3-18c09e049a99.png">
### bunlded code size
![image](https://user-images.githubusercontent.com/20334500/175472445-61af3b1e-c7d1-421e-9b9e-9292490cd4d7.png)

@odoe   i try to use ESM,and i prefer to use ESM,but i am cofused to the build time and bundled code size,maybe the esm cdn is a  good choice , but i can't import directly, i should inject thme to html when i build the project

**Comment by odoe** [comment]
The ESM CDN isn't for production apps, it's too slow to load all those unbundled files.

The built folder size isn't really much of an issue unless you have some size restrictions for deployment. Runtime use of JavaScript should be the main concern.

The JSAPI uses a lot of dynamic imports

```js
const module = await import('./module_a.js`);
```

Each of these becomes their own bundle file with build tooling. Some build tooling will generate more bundles from those if needed. This has a lot to do with Portal items, for example, when a WebMap is used, we don't know what layers are needed until it's loaded, so modules get loaded dynamically.

8 seconds for a production build time is good, or is that your dev build time? Webpack is not the fastest in that regard simply due to the number of files in the JSAPI.

If you want to speed up build times a bit, you can replace babel-loader with [esbuild-loader](https://www.npmjs.com/package/esbuild-loader).  I wouldn't worry about production build times, they are not run as often as dev builds.


Your application is going to be more optimized with ESM than using esri-loader with the CDN in 95% of cases. If you look at runtime js loads, it's the only real way to measure.

**Comment by webmapLee** [comment]
yes , maybe i can use other transformer tools like swc-loader or esbuild-loader,but i have used some babel-loader plugins,and there aren't corresponding plugin in swc-loader or esbuild-loader.  of course, i can try to develop the corresponding plugings one day,now  i  still use esri-loader,  i  will continue to pay attention to  the bundle sckeme for @arcgis/core, i will try the esm package @arcgis/core in my new project, thank you for your patience in discussing it

**Comment by andygup** [comment]
Closing. For new projects we recommend using @arcgis/core ES modules. More information is available in the SDK Developer Tooling Guide Topic: https://developers.arcgis.com/javascript/latest/es-modules/
