### ISSUE TITLE
Please package as Commonjs\es6 

### ISSUE THREAD

**Issue by dcworldwide** [Esri/jsapi-resources#50]
The majority of the js developer ecosystem centers around NPM and commonjs / es6 modules. As you've already provided a bower package solution, could you please provide a commonjs/es6 soltuion that we can simply NPM install? 

This would literally be a dream come true for those of us who belong to a growing community of developers choosing webpack / rollupjs.  As a value add, both of those bundler techs support tree shaking and dead code elimination. So if you're only using the map from the js api, only the map and it's dependencies will be packaged with the 'compiled' app. So no need to provide custom api builds.

**Comment by odoe** [comment]
Unfortunately, providing the JSAPI as an NPM module will not solve the issue of having it work with webpack or other build tools that could use node_modules. The API itself is still dependent on Dojo and AMD modules to dynamically load data as needed. This is due to needs such as i18n, lazy-loading and so on to keep the API builds at a reasonable size.

Although we use TypeScript heavily for 4.x (not all of it), we do not use it for 3.x, so we could not ship it as cjs or es6 at this point. Plus es6 minification is still not at a mature stage yet (at least not in uglify), and that is a requirement to publish the JSAPI.

It's on our radar though, and we test on a regular basis the different ways this could be accomplished.

**Comment by dcworldwide** [comment]
Personally, I think the api should be split. An esri-js-core (non dojo) and a esri-js-ui (dojo) lib. This is similar to how jquery and jquery ui is packaged. That would solve many problems / limitations with the current packaging.

**Comment by jgravois** [comment]
just to update this issue.  a few weeks ago the team shared documentation for shoehorning an npm install of the JSAPI that points at GitHub tags.

https://geonet.esri.com/community/developers/web-developers/arcgis-api-for-javascript/blog/2017/04/13/npm-and-arcgis-api-for-javascript-43

they have plans to publish `4.4` to npm. this will simplify the process outlined in the blog, but still not automatically make the API 'webpack ready'.

**Comment by zbennett10** [comment]
Are there any updates to this issue?

**Comment by odoe** [comment]
None as of yet. Still work to be done on the API.

**Comment by tomwayson** [comment]
@zbennett10 in the mean time, there's always https://github.com/Esri/esri-loader/ which provides an ES module that you can `import` that will then allow you to lazy load the ArcGIS API and use it's modules in non-Dojo apps.

**Comment by zbennett10** [comment]
@odoe  @tomwayson  thanks!

**Comment by odoe** [comment]
We have a webpack plugin now that will bundle the API with your Webpack builds. https://github.com/Esri/arcgis-webpack-plugin

**Comment by andygup** [comment]
Closing. We also now have an actual ES Modules build: https://developers.arcgis.com/javascript/latest/guide/es-modules/
