### ISSUE TITLE
Setting "visible" property on Graphic object results in error on (SceneLayer) layer.

### ISSUE THREAD

**Issue by shenningsgard** [Esri/jsapi-resources#67]
If a graphic is returned as part of a call to "`[mySceneLayer].queryFeatures()`", a call to "`[myGraphic].visible = [true/false]`" will result in an error "`TypeError: this.layer.graphicChanged is not a function`".

Digging into the (minified) code, it appears that the call to "`_notifyLayer()`" within "`esri/Graphic`", which in turn calls "`this.layer.graphicChanged()`", is the culprit:

`Object.defineProperty(a.prototype, "visible", {
  set: function(b) {
    var a = this._get("visible");
    a !== b && (this._set("visible", b),
    this._notifyLayer("visible", a, b))
  },
    enumerable: !0,
    configurable: !0
});`

According to the API docs, it seems this should be a valid call.

**Comment by bsvensson** [comment]
Hi @shenningsgard - thank you for your interest in the ArcGIS API for JavaScript.  Apologies for the late response.

As mentioned in the issue guideline, if you have generic requests for assistance with the [ArcGIS API for Javascript](http://js.arcgis.com), it's better to use one the below avenues instead of this repo (which is related to the TypeScript definitions and other files in this repo).

* Esri Tech Support - https://support.esri.com/contact-tech-support
* the Esri community on GeoNet - https://geonet.esri.com/community/developers/web-developers/arcgis-api-for-javascript

Cheers,
Bjorn

**Comment by shenningsgard** [comment]
Whoa, dug up from the grave! Thanks for getting to this, Bjorn :) I'm sure this issue has since been fixed any way, but will make sure the other GeoComm devs know the proper channels for this type of feedback in the future!

Cheers,
Steve
